#ifndef UNTITLED4_ELEMENTSDEFINITION_H
#define UNTITLED4_ELEMENTSDEFINITION_H
#define GRASS_TEXTURE "../assets/grass.png"
#define PLAIN_TEXTURE "../assets/plain.png"
#define TRAIL_TEXTURE "../assets/trail.png"
#define BLACK_GHOST_TEXTURE "../assets/black_ghost.png"
#define WHITE_GHOST_TEXTURE "../assets/white_ghost.png"
#define RED_GHOST_TEXTURE "../assets/red_ghost.png"
#define BROWN_GHOST_TEXTURE "../assets/brown_ghost.png"
#define START_TEXTURE "../assets/start.png"
#define FINISH_TEXTURE "../assets/finish.png"
#define MENU_BG_TEXTURE "../assets/bg_menu.png"
#define PLAYER_TEXTURE "../assets/player.png"
#define TEXT_FONT "../assets/text_font.TTF"
#define BUTTON_RELOAD "../assets/button_restart.png"
#define BUTTON_EXIT "../assets/button_exit.png"
#define BUTTON_MENU "../assets/button_menu.png"
#define BUTTON_CONTINUE "../assets/button_continue.png"
#define BUTTON_PLAY "../assets/button_play.png"
#define BUTTON_OPTIONS "../assets/button_option.png"
#define BUTTON_LOAD_GAME  "../assets/button_load_game.png"
#define BUTTON_PAUSE_CONTINUE "../assets/button_pause_continue.png"
#define BUTTON_SAVE "../assets/button_save.png"
#define CANNON_BLUE_TEXTURE "../assets/cannon.png"
#define CANNON_ORANGE_TEXTURE "../assets/cannon_orange.png"
#define CANNON_BLACK_TEXTURE "../assets/cannon_black.png"
#define BG_BUTTONS "../assets/bg_buttons.png"
#define BUTTON_CANNON_BLUE "../assets/button_cannon_blue.png"
#define BUTTON_CANNON_ORANGE "../assets/button_cannon_orange.png"
#define BUTTON_CANNON_BLACK "../assets/button_cannon_black.png"
#define HEALTH_TEXTURE "../assets/health.png"
#define BG_GAME_OVER "../assets/bg_gameOver.png"
#define BG_GAME_WIN "../assets/bg_win.png"
#include <SFML/Graphics.hpp>

#endif //UNTITLED4_ELEMENTSDEFINITION_H
